export enum ClientListCommandFlags {
    INCLUDE_UNIQUE_ID,
    INLCUDE_AWAY_DATA,
    INCLUED_VOICE_DATA,
    INCLUED_TIMES_DATA,
    INCLUED_GROUPS_DATA,
    INCLUED_INFO_DATA,
    INCLUED_COUNTRY_DATA,
    INCLUED_IP,
    INCLUED_BADGES_DATA
}
